spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
server:
  port: 8080